In [4]:
import numpy as np


In [6]:
arr=np.array([1,2,3,4,5])
#np.array([1,2,3,4,5]) we have to save them inside a variable 
arr #in order to print we just have to write the variable name 

array([1, 2, 3, 4, 5])

In [1]:
lis=[1,2,3]
lis # it is list upper one was array 

[1, 2, 3]

In [2]:
a=[1,2,3,"hello"]
a

[1, 2, 3, 'hello']

In [6]:
np.array(a)
# it will convert all the things to same data type 
# as we know numpy only taskes same data type so thats why it converted numbers into integers 

array(['1', '2', '3', 'hello'], dtype='<U21')

In [11]:
# creating 2d list 
# 2d list are not contigous memory block they store the pointer of next block 
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)
# now this is converted into contigous block of memory

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# to create array of your desired data type 
z=np.array([1,2,3],dtype=float)
z
# you can see float dtaa type is created

array([1., 2., 3.])

# Array generation

In [16]:
arr=np.arange(1,10,2)
arr
# it is used to geenrate the array in that range 

array([1, 3, 5, 7, 9])

In [18]:
arr=np.zeros(6)
arr
# it is used to generate zeros 

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr=np.zeros((4,8))
arr
# dont do zeros(4,8) always do zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr=np.linspace(1,5,4)
arr
# it gives the same space between numbers 
# like 1->5 4 elements then exactly same space elements 
# 1 is lower range , 5 is upper range and 4 is no of items 

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [9]:
np.identity(3)
# gives the identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random number geneartion 

In [27]:
np.random.rand(5)
# this is value inside normalization

array([0.25314756, 0.57848136, 0.30766933, 0.3635859 , 0.09449957])

In [28]:
np.random.randint(5)
# from 0 to 5 it will genearte a random number 

2

In [30]:
np.random.randint(10,20,10)
# generate random numbers inside this range and last no is number of random integers means it will genearte 10 random integers 

array([18, 17, 12, 13, 11, 16, 11, 16, 16, 16], dtype=int32)

In [8]:
np.random.random((3,2))


array([[0.87832886, 0.05171953],
       [0.40683274, 0.18116316],
       [0.49089471, 0.19743782]])

# Array Attributes<!--  -->

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr.shape
# how many rows and columns

(2, 3)

In [36]:
arr.size
# mxn

6

In [12]:
# in order to find dimensions of array 
arr.ndim

2

In [13]:
arr.itemsize
# default is integer64 it is using 8 bytes 

8

In [14]:
arr.dtype

dtype('int64')

In [15]:
# changing data types 
# suppose we have int 64 we can change it to int 32
arr.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Array Methods

In [37]:
arr
# previous array

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.max()
# 6 is largest

np.int64(6)

In [40]:
arr.sum()

np.int64(21)

In [41]:
np.sum(arr,axis=1)
# axis = 1 means sum of row of that array 
# axis = 0 means sum of columns of that array 

array([ 6, 15])

In [42]:
arr.mean()

np.float64(3.5)

In [44]:
arr.std()
# standard deviation

np.float64(1.707825127659933)

In [45]:
arr.argmax()
# what is the index of maximum element

np.int64(5)

In [17]:
arr.sum()
# gives sum of whole matrix 

np.int64(21)

# reshaping and resizing

In [50]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
# suppose if we want to convert this one D into other dimension
arr=arr.reshape(6,5)
# for the reshape means changing dimension then number of elements should be same
# resize means just assign it a variable and save in it so whenever we will call that variable we will get the new order arra

In [54]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])