In [6]:
import numpy as np


In [7]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
arr[6]
# gives teh 6th index

np.int64(7)

In [9]:
arr1=arr[1:4]
arr1

array([2, 3, 4])

In [10]:
arr_slice=arr[3::2]
arr_slice
# 2 means the steps it taking or jumping 

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

# indexing and resizing and slicing of matrix 

In [11]:
arr=np.arange(1,31).reshape(6,5)
arr
# its just like previous one where we reshaped here we also reshaped while creating

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[5]
# complete row 

array([26, 27, 28, 29, 30])

In [14]:
arr[0][4]

np.int64(5)

In [15]:
arr[0,0]
# we can also do by this one 

np.int64(1)

# slicing in 2d

In [16]:
arr[0:2,2:4]
# in slicing we know the last index is not included 

array([[3, 4],
       [8, 9]])

In [17]:
arr[:,2]
# slicing a column just like we did arr[0,:] for rows 
# : means that we want all items of column or row
# arr[:,2] it means we want all rows and 1st column ... because column contain all rows

array([ 3,  8, 13, 18, 23, 28])

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
# doing jumping
arr[::2,::3]
# single colon means all elements but we dont want all elements we want jump of two elements like 
# oth row 2nd row and 4th row ... similary for columns we do this 

array([[ 1,  4],
       [11, 14],
       [21, 24]])

In [22]:
arr[1,::3] # means first row but 3 jump elements

array([6, 9])

# slicing in 3d 

In [24]:
arr3=np.arange(27).reshape(3,3,3)
# means that there are 3 2d arrays 
# first 3 is showing no of arrays middle is showing rows and last is shwoing columns 
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
arr3[0,1,:]
# here 0 is showing first 2d array 
#  1 is shwoing the 2nd row odf first 2d array and colon is shwoing all columns 

array([3, 4, 5])

In [33]:
arr3[1,:,1]
# only 2nd column of 2nd matrix

array([10, 13, 16])

### jumping in matrices in 3d tensor or for choosing 2 matrices the method is same 

In [36]:
# suppose if we want to select first matrix and last matrix 
arr3[0::2,0:2,0:2]
# hence for jumping we have to use our previous concept using 2 colons 
# as we know the first element like 0::2 determines our matrices 

array([[[ 0,  1],
        [ 3,  4]],

       [[18, 19],
        [21, 22]]])

## iterating in numpy array 


In [37]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
for i in arr:
 print(i)
# it will print all the rows 

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]


In [42]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
for i in arr1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
# for 3d 
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
for i in arr3:
    print(i)
    # it gives 2d matrices 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [48]:
# to get all the items 
for i in np.nditer(arr3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# boolean indexing

In [34]:
arr=np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
bool_index=arr %2==0
bool_index
# it will give ans in true or false 

array([False,  True, False,  True, False,  True, False,  True, False])

In [35]:
arr=arr[bool_index]
arr
# here we will get even numbers only that is boolean indexing 

array([12, 14, 16, 18])