In [4]:
import numpy as np 

## arithematic operations

In [3]:
a1=np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [4]:
a2=np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [5]:
a3=a1+a2
a3

array([ 7,  9, 11, 13, 15])

In [6]:
a4=a2-a1
a4

array([5, 5, 5, 5, 5])

In [9]:
a5=a1//a2
a5
# integers 

array([0, 0, 0, 0, 0])

In [10]:
a1**2
# powering 

array([ 1,  4,  9, 16, 25])

### broadcasting

In [17]:
l=[1,2,3,4]
arr=np.array(l)

In [12]:
arr

array([1, 2, 3, 4])

In [18]:
# suppose if i want to add 10 in each number we have to run loop in case of l 
for i in l:
    print(i+10)


11
12
13
14


In [19]:
# but in case of arrays means in broadcasting we can simply do this 
arr+10
# we can also do this in matrices


array([11, 12, 13, 14])

#### deeep copy and shallow copy 

In [5]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
# slicing
slice=a[:6]
slice=slice*2
slice
# there is no chnage in original array 

array([ 2,  4,  6,  8, 10, 12])

In [7]:
b=a
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a
# in case of slicing teh original does not chnage but in case of copying whole array and then changing second one then it will change 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
c=a.copy()
# it will do shallow copy not deep one 

In [10]:
c[0]=1

In [11]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# relational operations


In [13]:
a<25
# its scalar operations when we do something with numpy array like adding or subtracting or comparing things

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

# matrix multiplication 

In [47]:
a=np.array([[1,2],[4,5]])
a

array([[1, 2],
       [4, 5]])

In [46]:
b=np.array([[1,2],[4,5]])
b

array([[1, 2],
       [4, 5]])

In [48]:
a @ b
# it will do matrix multiplication

array([[ 9, 12],
       [24, 33]])

In [51]:
a.T
# it will give transpose of matrix

array([[1, 4],
       [2, 5]])

In [52]:
a

array([[1, 2],
       [4, 5]])

# advance array manipulation

### stacking 

In [53]:
a=np.array([1,2,3,4,5])
# we cannnot use matrices , here we have to use vectors 

In [54]:
b=np.array([6,7,8,9,5])

In [57]:
np.vstack((a,b))
# it will stack bvertically 

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 5]])

In [61]:
np.hstack((a,b))
# horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [62]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 5]])

### spliting 

In [64]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [72]:
a=np.vsplit(c,4)
# it will split it in 4 equal parts
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [73]:
for i in a:
    print(i)

# it will print the 4 arrays in a 

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
