In [1]:
import numpy as np

In [3]:
arr=np.random.random((3,3))
arr=np.round(arr*100)
arr

# np.round gives round off integer .. like we do arr*100 we will get ans in float to get in integer i will use np.round()

array([[74., 66., 71.],
       [51., 82., 48.],
       [67., 71., 38.]])

In [4]:
arr.max()

np.float64(82.0)

In [5]:
np.max(arr)
# both are same things 

np.float64(82.0)

In [6]:
arr.max(axis=0)

array([74., 82., 71.])

In [7]:
np.max(arr,axis=0)

array([74., 82., 71.])

In [10]:
arr.prod(axis=0)
# gives the product of columns 

array([252858., 384252., 129504.])

In [11]:
np.prod(arr,axis=1)
# produt of rows 

array([346764., 200736., 180766.])

In [13]:
np.sin(arr)

array([[-0.98514626, -0.02655115,  0.95105465],
       [ 0.67022918,  0.31322878, -0.76825466],
       [-0.85551998,  0.95105465,  0.29636858]])

In [14]:
np.prod(arr[0])

np.float64(346764.0)

In [15]:
np.log(arr)

array([[4.30406509, 4.18965474, 4.26267988],
       [3.93182563, 4.40671925, 3.87120101],
       [4.20469262, 4.26267988, 3.63758616]])