In [6]:
# np.sort 
import numpy as np
a=np.random.randint(1,100,15).reshape(5,3)
np.sort(a,axis=0)
# column wise sorting 

array([[35, 14, 16],
       [40, 22, 36],
       [45, 41, 71],
       [80, 56, 90],
       [93, 99, 90]], dtype=int32)

In [7]:
# append function
a

array([[80, 22, 90],
       [93, 56, 16],
       [45, 41, 36],
       [35, 14, 90],
       [40, 99, 71]], dtype=int32)

In [9]:
np.append(a,100)
# 100 is appened at the end 

array([ 80,  22,  90,  93,  56,  16,  45,  41,  36,  35,  14,  90,  40,
        99,  71, 100])